# numpy, sympy not whitelisted by travis; need sudo
sudo: true

language: python

python:
    - "3.5"
#    - "3.3"
#    - "3.4"
#    - "3.2"


#virtualenv:
#  system_site_packages: true

before_install:
  - sudo apt-get install -y python-numpy python3-numpy

install:
  - pip install clipboard
  - pip install .

script:
  - nosetests --with-doctest --doctest-tests

#--doctest-extension= 'array_to_latex'
